apiVersion: v1
kind: Secret
metadata:
  name: jeonbongjun-secrets
  namespace: jeonbongjun # 위에서 만든 네임스페이스 지정
type: Opaque # 일반적인 비밀 정보 타입
data:
  # !! 실제 값은 Base64 인코딩된 문자열로 바꿔야 합니다 !!
  MYSQL_ROOT_PASSWORD: bWFyaWEK # 예: cm9vdHBhc3N3b3Jk
  DEEPSEARCH_API_KEY: ZDk3MWRlZjIxYTJkNGM3NjgyZjVlMzQwZWMxN2VhZmM=   # 예: ZDk3MWRlZjIxYTJkNGM3NjgyZjVlMzQwZWMxN2VhZmM=
  # 필요하다면 다른 API Key (Redis 비밀번호 등) 추가